/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const $localStorage: typeof import('./src/composables/stores')['$localStorage']
  const $theme: typeof import('./src/composables/stores')['$theme']
  const afterUpdate: typeof import('svelte')['afterUpdate']
  const beforeUpdate: typeof import('svelte')['beforeUpdate']
  const createEventDispatcher: typeof import('svelte')['createEventDispatcher']
  const getAllContexts: typeof import('svelte')['getAllContexts']
  const getContext: typeof import('svelte')['getContext']
  const global: typeof import('./src/composables/stores')['global']
  const hasContext: typeof import('svelte')['hasContext']
  const loadData: typeof import('./src/composables/stores')['loadData']
  const localStorage: typeof import('./src/composables/stores')['localStorage']
  const onDestroy: typeof import('svelte')['onDestroy']
  const onMount: typeof import('svelte')['onMount']
  const populatePage: typeof import('./src/composables/markUp')['populatePage']
  const processImage: typeof import('./src/composables/stores')['processImage']
  const router: typeof import('./src/composables/router')['router']
  const searchFields: typeof import('./src/composables/stores')['searchFields']
  const setContext: typeof import('svelte')['setContext']
  const setupListeners: typeof import('./src/composables/markUp')['setupListeners']
  const tick: typeof import('svelte')['tick']
  const toggleTheme: typeof import('./src/composables/localStorage')['toggleTheme']
  const writeHomePage: typeof import('./src/composables/markUp')['writeHomePage']
  const writeJobList: typeof import('./src/composables/markUp')['writeJobList']
  const writeMainPage: typeof import('./src/composables/markUp')['writeMainPage']
}
